apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-ksa
  namespace: production
  annotations:
    iam.gke.io/gcp-service-account: blakjaks-backend@blakjaks-production.iam.gserviceaccount.com
